[5] Whilst we are here, make our guards approach consistent between all commands

diff --git a/commands/host/devkit-db-import b/commands/host/devkit-db-import
--- a/commands/host/devkit-db-import
+++ b/commands/host/devkit-db-import
@@ -22,10 +22,13 @@ for ARG in "$@"; do
   esac
 done
 
-# Validate
+# Guards
 DIRECTORY_PATH="$DDEV_APPROOT/$DIRECTORY"
 
-[[ -d "$DIRECTORY_PATH" ]] || { echo "Directory not found. Cannot locate dump files in '$DIRECTORY_PATH'."; exit 1; }
+if [[ ! -d "$DIRECTORY_PATH" ]]; then
+  echo "Directory not found. Cannot locate dump files in '$DIRECTORY_PATH'."
+  exit 1
+fi
 
 shopt -s nullglob
 FILES=(
@@ -44,7 +47,10 @@ FILES=(
 )
 shopt -u nullglob
 
-(( ${#FILES[@]} > 0 )) || { echo "Cannot locate dump files in '$DIRECTORY_PATH'."; exit 1; }
+if (( ${#FILES[@]} == 0 )); then
+  echo "Cannot locate dump files in '$DIRECTORY_PATH'."
+  exit 1
+fi
 
 # Prompt
 echo "Choose a dump file to import from '$DIRECTORY_PATH':"
